### ISSUE TITLE
C file containing only `typedef int x;` causes segfault

### ISSUE THREAD

**Issue by electrodude** [totalspectrum/spin2cpp#310]
Save the following into `typedef_bug.c`:
```c
typedef int x;
```

and then run the latest flexspin on it:
```
$ flexspin typedef_bug.c
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2022 Total Spectrum Software Inc.
Version 5.9.20-beta-v5.9.19-8-g1cffcf72 Compiled on: Nov 14 2022
typedef_bug.c
typedef_bug.c
Segmentation fault
```

Expected behavior:
No segfault.  Probably no error, either: while C doesn't permit empty translation units, it does permit ones with nothing but typedefs.

**Comment by electrodude** [comment]
Here's what GDB has to say:
```
$ gdb ./build/flexspin
Reading symbols from ./build/flexspin...
(gdb) r typedef_bug.c 
Starting program: ${SPIN2CPP}/build/flexspin typedef_bug.c
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2022 Total Spectrum Software Inc.
Version 5.9.20-beta-v5.9.19-8-g1cffcf72 Compiled on: Nov 14 2022
typedef_bug.c
typedef_bug.c

Program received signal SIGSEGV, Segmentation fault.
FindSymbolEx (table=0x88, name=name@entry=0x5555555fb47f "_STACK", forceCaseSens=forceCaseSens@entry=0) at symbol.c:42
42          int nocase = ((table->flags & SYMTAB_FLAG_NOCASE) != 0) && !gl_caseSensitive;
(gdb) bt
#0  FindSymbolEx (table=0x88, name=name@entry=0x5555555fb47f "_STACK", forceCaseSens=forceCaseSens@entry=0) at symbol.c:42
#1  0x000055555556fe79 in FindSymbol (name=0x5555555fb47f "_STACK", table=<optimized out>) at ./symbol.h:91
#2  DoPropellerPostprocess (fname=fname@entry=0x555555cfce70 "typedef_bug.binary", eepromSize=0) at frontends/common.c:1109
#3  0x000055555556da0a in ProcessCommandLine (cmd=cmd@entry=0x5555556b0560 <cmd_base>) at cmdline.c:331
#4  0x000055555556cc6c in main (argc=<optimized out>, argv=0x7fffffffcea8) at flexspin.c:547
(gdb) f 1
#1  0x000055555556fe79 in FindSymbol (name=0x5555555fb47f "_STACK", table=<optimized out>) at ./symbol.h:91
91          return FindSymbolEx(table,name,0);
(gdb) f 2
#2  DoPropellerPostprocess (fname=fname@entry=0x555555cfce70 "typedef_bug.binary", eepromSize=0) at frontends/common.c:1109
1109        sym = FindSymbol(&current->objsyms, "_STACK");
(gdb) list
1104        current = GetTopLevelModule();
1105        // we are at the end of compilation, check for stack info in a
1106        // case insensitive manner
1107        save_casesensitive = gl_caseSensitive;
1108        gl_caseSensitive = 0;
1109        sym = FindSymbol(&current->objsyms, "_STACK");
1110        if (sym && sym->kind == SYM_CONSTANT) {
1111            reserveSize += LONG_SIZE * EvalConstExpr((AST *)sym->val);
1112        }
1113        sym = FindSymbol(&current->objsyms, "_FREE");
(gdb) p GetTopLevelModule()
$1 = (Module *) 0x0
(gdb) list GetTopLevelModule 
1573
1574    // fetch the top level module
1575    Module *
1576    GetTopLevelModule(void)
1577    {
1578        return allparse;
1579    }
1580
1581    //
1582    // check for whether a variable of type T must go on the stack
(gdb) p allparse 
$2 = (Module *) 0x0
(gdb)
```

[frontends/common.c:1104-1109](https://github.com/totalspectrum/spin2cpp/blob/master/frontends/common.c#L1104-L1109) does `current = GetTopLevelModule();`, which returns `allparse` which is `NULL`, and then proceeds to pass the bogus `&current->objsyms` to `FindSymbol`, which forwards it to `FindSymbolEx`, which dereferences it via `table->flags` and dies.

**Comment by totalspectrum** [comment]
Thanks for the detailed bug report. I think this is fixed in the github sources now.
